stm_nand: Fix renamed registers in debug code
Commit 154165d353c9525380a6e16530b0d51cc5e10de1
    stm_nand: updates to NAND controller register definitions
renamed a number of macros which refer to NAND controller registers.
However a number of usages of these macros in debug code were not updated,
which resulted in the following compilation errors:
drivers/mtd/nand/stm_nand_flex.c: In function 'flex_print_regs':
drivers/mtd/nand/stm_nand_flex.c:891:23: error: 'NANDHAM_INTERRUPT_ENABLE' undeclared (first use in this function)
drivers/mtd/nand/stm_nand_flex.c:891:23: note: each undeclared identifier is reported only once for each function it appears in
drivers/mtd/nand/stm_nand_flex.c:893:23: error: 'NANDHAM_INTERRUPT_STATUS' undeclared (first use in this function)
drivers/mtd/nand/stm_nand_flex.c:895:23: error: 'NANDHAM_INTERRUPT_CLEAR' undeclared (first use in this function)
drivers/mtd/nand/stm_nand_flex.c:897:23: error: 'NANDHAM_INTERRUPT_EDGECONFIG' undeclared (first use in this function)
drivers/mtd/nand/stm_nand_flex.c:905:23: error: 'NANDHAM_FLEXMODE_CONFIG' undeclared (first use in this function)
drivers/mtd/nand/stm_nand_flex.c:907:23: error: 'NANDHAM_MUXCTL' undeclared (first use in this function)
drivers/mtd/nand/stm_nand_flex.c:909:23: error: 'NANDHAM_CSN_ALTERNATE' undeclared (first use in this function)

Update the code to the new definitions. Note that the macro
EMINAND_CSN_ALTERNATE was removed completely in the previous commit,
so remove the corresponding print (of NANDHAM_CSN_ALTERNATE) as well.

Signed-off-by: Stuart Menefy <stuart.menefy@st.com>