sh_stm: Fix build of STM cpufreq driver when configured as module.
To correctly build the STM cpufreq driver as module, it needs to export
some kernel symbol from cpufreq subsystem to fix the following link errors:

ERROR: "cpufreq_gov_performance" [arch/sh/kernel/cpu/sh4/cpufreq-stm.ko] undefined!
...
ERROR: "cpufreq_gov_userspace" [arch/sh/kernel/cpu/sh4/cpufreq-stm.ko] undefined!
...
ERROR: "cpufreq_gov_ondemand" [arch/sh/kernel/cpu/sh4/cpufreq-stm.ko] undefined!
...
ERROR: "cpufreq_gov_conservative" [arch/sh/kernel/cpu/sh4/cpufreq-stm.ko] undefined!

Signed-off-by: Carmelo Amoroso <carmelo.amoroso@st.com>