sh: Fix kernel build when PMB_FIXED is configured
When PMB_FIXED is used, fixed_pmb_init() is called,
so one should not call pmb_init(). This results
in undefined symbol on link as below:

  LD      .tmp_vmlinux1
arch/sh/kernel/built-in.o: In function `sh_cpu_init':
(.init.text+0x1714): undefined reference to `pmb_init'
make: *** [.tmp_vmlinux1] Error 1

See: Bugzilla #9921

Signed-off-by: Stas Sergeev <stsp@aknet.run>
Signed-off-by: Carmelo Amoroso <carmelo.amoroso@st.com>