stm_pad: Add missing export symbols required by hcd-stm module
It needs to export stm_pad_claim and stm_pad_release required by
hcd-stm module

It fixes the following errors

ERROR: "stm_pad_claim" [drivers/usb/host/hcd-stm.ko] undefined!
ERROR: "stm_pad_release" [drivers/usb/host/hcd-stm.ko] undefined!

Signed-off-by: Carmelo Amoroso <carmelo.amoroso@st.com>
Signed-off-by: Stuart Menefy <stuart.menefy@st.com>